import "./globals.css";

import Footer from "components/nav/Footer";

export const dynamic = "force-dynamic";

export const metadata = {
	title: "SALE-E",
	description: "Generated by Next.js with Supabase",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div>
					<main>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
